//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int MoveX = 0;
    public const int MoveY = 1;
    public const int Action = 2;
    public const int Jump = 3;
    public const int MenuX = 4;
    public const int MenuY = 5;
    public const int MenuAccept = 6;
    public const int MenuCancel = 7;
    public const int _count = 8;
}
